---
title: "Flashcard Package Functions"
author: "Alex"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This document will carry the functions that will eventually be used in my created package for the R programming class.

## Flashcard Input
This first function is used to enter in the flashcaard data into a data frame for use later on.

```{r}
flashcards <- function() 
  flashcards_data <- data.frame(
    question = character(),
    answer = character(),
    correct = integer(),
    total = integer(),
    stringsAsFactors = FALSE
  )
```
Z
## Menu
This second function can be used to select any of the various functions that will eventually be built for the project.
```{r}
  
  main_menu <- function() {
    repeat {
      choice <- menu(c("Add Flashcards", "Study Flashcards", "View Progress", "Exit"), title = "Flashcard Program Menu")
      switch(choice,
             add_flashcards(),
             study_flashcards(),
             view_progress(),
             break)
    }
  }

```

  

